POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbG1hbmtheXR0aXNAZW1haWwuZmkiLCJpZCI6MSwiaWF0IjoxNjk0NzU5MjM0fQ.UUOUPxvt3eKaz5v5HIy7KO1_glvPEjqkduHp8VP4IWQ

{
  "author": "Wilma Koira",
    "url": "wwww.wssww",
    "title": "Koira blogi"
}