POST http://localhost:3001/api/readinglists
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbm5pbmtheXR0aXNAZW1haWwuZmkiLCJpZCI6MSwiaWF0IjoxNjk0NzY1MTM4fQ.kCrTaafd5XUF4zAyG_cr9YbzhxFPypeS76WHHIzqOPQ

{
  "blogId": "1",
    "userId": "2"
}